### ISSUE TITLE
Why do you promisify mongo API?

### ISSUE THREAD

**Issue by danielo515** [metoikos/hapi-multi-mongo#1]
It is here:
https://github.com/metoikos/hapi-multi-mongo/blob/master/lib/index.js#L4

The latest mongo driver for node is compatible with promises with the addition that it is retro-compatible with callbacks. So, it is not needed to promisify the API.

I'm not sure if `promisifyAll` is extensible to the objects returned by the API methods promisified. But if so, you are removing a retro-compatible feature that comes for free in which mongo team worked hard

**Comment by metoikos** [comment]
Hello Daniel.

The motivation behind this choice was to use same promise library all over in the project. We are using many libraries and many of them uses its own implementation or something different from bluebird, so we want to make sure all promise behaviours should be them same.  

I've extracted this piece of code from a bigger project (which is an adserver system) and many part of the code remained same because, only this way I can claim this code battle tested because the very same code handles 10-20 millions request every day.

But I got your point here, the better approach here let the native mongo to use its own promises and let users to choice its own implementation through **promiseLibrary** option on MongoClient  definition.

I'm going to test this implementation changes and after that i'll push new updates,

thanks for the heads up.
