### ISSUE TITLE
connect to replica set?

### ISSUE THREAD

**Issue by emckean** [metoikos/hapi-multi-mongo#2]
Hi! Does 'Connection options can be a single object' mean that hapi-multi-mongo doesn't connect to uris of the format "mongodb://<dbuser>:<dbpassword>@server1,server2/<dbname>?replicaSet=replicaSetName"? 

When I try a URI of this format I get the error "An error occurred during connection uri iteration"

Thanks for any suggestions!

**Comment by emckean** [comment]
I figured out the issue and submitted a pull request. (I like regular expressions  ¯\_(ツ)_/¯)

**Comment by metoikos** [comment]
Thanks for the pr. I couldn't add replica set tests to test runner but I checked locally with a docker mongo replica and it worked, so I think everyone will be fine. Thank you again to bring this up 👏
We all love Regex so much! :)

You can install updated version in hapi-multi-mongo@4.1.0

Fixed in #3
